GET http://localhost:5001/superheroes?page=1&limit=10

###

GET http://localhost:5001/supervillains?page=1&limit=10

###

GET http://localhost:5001/superheroes/Batman

###

GET http://localhost:5001/supervillains/Brainiac

###

POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "name": "Batman",
    "debut": "01-01-1932",
    "secretIdentity": "Bruce Wayne"
}

###

POST http://localhost:5001/supervillains
Content-Type: application/json

{
    "name": "Joker",
    "debut": "01-01-1932"
}

###

POST http://localhost:5001/supervillains
Content-Type: application/json

{
    "name": "Brainiac",
    "debut": "01-01-1934"
}

###

POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "name": "Superman",
    "debut": "01-01-1933",
    "secretIdentity": "Clark Kent"
}

###

POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "name": "The Flash",
    "debut": "01-01-1934",
    "secretIdentity": "Barry Allen"
}

###

POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "name": "Spiderman",
    "debut": "01-01-1932",
    "secretIdentity": "Peter Parker"
}

###

//delete spiderman
DELETE http://localhost:5001/superheroes/644b157170658b89412c3b3e

###

//create new spiderman with wrong data
POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "name": "Spoderman",
    "debut": "01-01-1912",
    "secretIdentity": "Peter Porker"
}

###

//get spidermand id
GET http://localhost:5001/superheroes/Superman

###

PATCH http://localhost:5001/superheroes/645ac406ceee272640bc5bb7
Content-Type: application/json

{
    "name": "Spiderman"
}

###

PATCH http://localhost:5001/superheroes/645ac3fcceee272640bc5bb1
Content-Type: application/json

{
    "enemy": "645ad84fec8efb248297b31a"
}

###

PATCH http://localhost:5001/superheroes/645ac400ceee272640bc5bb3
Content-Type: application/json

{
    "enemy": "645ad86fec8efb248297b31e"
}

###

PATCH http://localhost:5001/supervillains/645ad86fec8efb248297b31e
Content-Type: application/json

{
    "enemy": "645ac400ceee272640bc5bb3"
}

###

//create new spiderman with wrong data
POST http://localhost:5001/supervillains
Content-Type: application/json

{
    "name": "ReverseFlash",
    "debut": "01-01-1912",
    "archNemesis": "645ac403ceee272640bc5bb5"
}

###

PATCH http://localhost:5001/superheroes/645ac403ceee272640bc5bb5
Content-Type: application/json

{
    "enemy": "645b0066d1a2b0386ae204ca"
}

###
GET http://localhost:5001/superheroes/Spiderman
